import React, { createContext, useContext, useState, ReactNode } from 'react';

// Translation interface
interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

// All translations
const translations: Translations = {
  en: {
    // Dashboard
    dashboard: 'Dashboard',
    home: 'Home',
    overview: '📊 Overview',
    totalProblems: 'Total Problems',
    pendingReview: 'Pending Review',
    approved: 'Approved',
    urgent: 'Urgent',
    quickActions: '⚡ Quick Actions',
    submitProblem: 'Submit Problem',
    viewAllProblems: 'View All Problems',
    browseProblems: 'Browse Problems',
    generateAI: 'Generate with AI',
    myProfile: 'My Profile',
    recentActivity: '📈 Recent Activity',
    viewAll: 'View All',
    seeAll: 'See All',
    justNow: 'Just now',
    minutesAgo: 'minutes ago',
    hoursAgo: 'hours ago',
    daysAgo: 'days ago',
    
    // Problems
    problems: 'Problems',
    problemStatements: 'Problem Statements',
    browseAllProblems: 'Browse all hackathon problems',
    allProblems: 'All Problems',
    mySubmissions: 'My Submissions',
    bookmarked: 'Bookmarked',
    searchProblems: 'Search problems...',
    filters: 'Filters',
    urgentOnly: 'Urgent Only',
    clearAll: 'Clear All',
    category: 'Category',
    difficulty: 'Difficulty',
    problemsFound: 'problems found',
    noProblemsFound: 'No problems found',
    tryAdjustingFilters: 'Try adjusting your filters or submit a new problem!',
    noProblems: 'No problems found',
    noProblemsSub: 'Be the first to submit a problem statement!',
    
    // Submit Problem
    submit: 'Submit',
    submitProblemStatement: 'Submit Problem Statement',
    problemTitle: 'Problem Title',
    enterTitlePlaceholder: 'Enter a clear and concise title',
    provideDetailedDescription: 'Provide a detailed description of the problem',
    constraints: 'Constraints',
    addConstraintPlaceholder: 'Add a constraint and press +',
    requirements: 'Requirements',
    addRequirementPlaceholder: 'Add a requirement and press +',
    addTagsPlaceholder: 'Add tags for better discovery',
    attachmentsOptional: 'Attachments (Optional)',
    uploadFilesOrImages: 'Upload Files or Images',
    problemSubmittedSuccess: 'Problem submitted successfully!',
    difficultyLevel: 'Difficulty Level',
    title: 'Title',
    description: 'Description',
    tags: 'Tags',
    attachments: 'Attachments',
    markAsUrgent: 'Mark as Urgent',
    
    // Mentor
    mentor: 'Mentor',
    mentorPanel: 'Mentor Panel',
    reviewAndManage: 'Review and manage submissions',
    reviewQueue: 'Review Queue',
    approvedProblems: 'Approved Problems',
    approve: 'Approve',
    reject: 'Reject',
    highlight: 'Highlight',
    assignToMe: 'Assign to Me',
    mentorAssigned: 'Mentor Assigned',
    highlighted: 'Highlighted',
    topPicks: 'Top Picks',
    all: 'All',
    pending: 'Pending',
    aiGenerator: 'AI Generator',
    
    // Profile
    profile: 'Profile',
    editProfile: 'Edit Profile',
    changePhoto: 'Change Photo',
    statistics: 'Statistics',
    submitted: 'Submitted',
    bookmarks: 'Bookmarks',
    approvedCount: 'Approved',
    settings: 'Settings',
    help: 'Help & Support',
    about: 'About',
    logout: 'Logout',
    
    // Settings
    settingsTitle: '⚙️ Settings',
    notifications: '🔔 NOTIFICATIONS',
    enableNotifications: 'Enable Notifications',
    receiveAllNotifications: 'Receive all notifications',
    emailNotifications: 'Email Notifications',
    receiveByEmail: 'Receive updates by email',
    pushNotifications: 'Push Notifications',
    receivePush: 'Receive push notifications',
    problemUpdates: 'Problem Updates',
    notifyProblemChanges: 'Notify when problems change',
    mentorFeedback: 'Mentor Feedback',
    notifyMentorReviews: 'Notify when mentors review',
    general: '🛠️ GENERAL',
    autoSaveDrafts: 'Auto-Save Drafts',
    autoSaveDraftsSub: 'Automatically save problem drafts',
    soundEffects: 'Sound Effects',
    soundEffectsSub: 'Play sounds for actions',
    language: 'Language',
    privacySecurity: '🔒 PRIVACY & SECURITY',
    privacySettings: 'Privacy Settings',
    dataUsage: 'Data Usage',
    accountSecurity: 'Account Security',
    clearCache: 'Clear Cache',
    
    // Language Modal
    selectLanguage: '🌍 Select Language',
    languageChanged: 'Language Changed',
    languageChangedMsg: 'Language has been changed successfully!',
    
    // Help
    helpTitle: '❓ Help & Support',
    commonQuestions: 'Common Questions',
    q1: 'How do I submit a problem?',
    a1: 'Navigate to the Submit tab and fill in the problem details. You can also attach files and mark urgent problems.',
    q2: 'How does the review process work?',
    a2: 'Mentors review submitted problems and can approve, reject, or request changes. You\'ll receive notifications about the status.',
    q3: 'Can I edit my submission?',
    a3: 'Yes, you can edit your submission before it\'s reviewed. Once approved, you\'ll need mentor permission to make changes.',
    q4: 'How do I become a mentor?',
    a4: 'Contact the hackathon organizers to request mentor privileges. Mentors can review and approve problem statements.',
    contactSupport: 'Contact Support',
    email: 'Email',
    phone: 'Phone',
    liveChatSoon: 'Live chat coming soon',
    needMoreHelp: 'Need more help?',
    contactTeam: 'Contact our support team and we\'ll get back to you within 24 hours.',
    
    // About
    aboutTitle: 'ℹ️ About HackIntake',
    version: 'Version',
    mission: '🎯 Mission',
    missionText: 'HackIntake is a comprehensive platform for managing hackathon problem statements. We empower organizers, mentors, and teams to collaborate effectively.',
    features: '✨ Features',
    featuresText: '• Submit and browse problem statements\n• AI-powered problem generation\n• Mentor review and approval system\n• Real-time dashboard updates\n• Dark mode support\n• Bookmark and track problems',
    team: '👥 Team',
    teamText: 'Built with ❤️ by the HackIntake team',
    website: 'Website',
    github: 'GitHub',
    twitter: 'Twitter',
    copyright: '© 2025 HackIntake. All rights reserved.',
    
    // Common
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    close: 'Close',
    ok: 'OK',
    yes: 'Yes',
    no: 'No',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
  },
  
  fr: {
    // Dashboard
    dashboard: 'Tableau de bord',
    home: 'Accueil',
    overview: '📊 Aperçu',
    totalProblems: 'Problèmes totaux',
    pendingReview: 'En attente de révision',
    approved: 'Approuvé',
    urgent: 'Urgent',
    quickActions: '⚡ Actions rapides',
    submitProblem: 'Soumettre un problème',
    viewAllProblems: 'Voir tous les problèmes',
    browseProblems: 'Parcourir les problèmes',
    generateAI: 'Générer avec IA',
    myProfile: 'Mon profil',
    recentActivity: '📈 Activité récente',
    viewAll: 'Voir tout',
    seeAll: 'Voir tout',
    justNow: 'À l\'instant',
    minutesAgo: 'il y a quelques minutes',
    hoursAgo: 'il y a quelques heures',
    daysAgo: 'il y a quelques jours',
    
    // Problems
    problems: 'Problèmes',
    problemStatements: 'Énoncés de problèmes',
    browseAllProblems: 'Parcourir tous les problèmes du hackathon',
    allProblems: 'Tous les problèmes',
    mySubmissions: 'Mes soumissions',
    bookmarked: 'Favoris',
    searchProblems: 'Rechercher des problèmes...',
    filters: 'Filtres',
    urgentOnly: 'Urgent uniquement',
    clearAll: 'Tout effacer',
    category: 'Catégorie',
    difficulty: 'Difficulté',
    problemsFound: 'problèmes trouvés',
    noProblemsFound: 'Aucun problème trouvé',
    tryAdjustingFilters: 'Essayez d\'ajuster vos filtres ou soumettez un nouveau problème!',
    noProblems: 'Aucun problème trouvé',
    noProblemsSub: 'Soyez le premier à soumettre un problème!',
    
    // Submit Problem
    submit: 'Soumettre',
    submitProblemStatement: 'Soumettre un énoncé de problème',
    problemTitle: 'Titre du problème',
    enterTitlePlaceholder: 'Entrez un titre clair et concis',
    provideDetailedDescription: 'Fournir une description détaillée du problème',
    constraints: 'Contraintes',
    addConstraintPlaceholder: 'Ajouter une contrainte et appuyez sur +',
    requirements: 'Exigences',
    addRequirementPlaceholder: 'Ajouter une exigence et appuyez sur +',
    addTagsPlaceholder: 'Ajouter des étiquettes pour une meilleure découverte',
    attachmentsOptional: 'Pièces jointes (facultatif)',
    uploadFilesOrImages: 'Télécharger des fichiers ou des images',
    problemSubmittedSuccess: 'Problème soumis avec succès!',
    difficultyLevel: 'Niveau de difficulté',
    title: 'Titre',
    description: 'Description',
    tags: 'Étiquettes',
    attachments: 'Pièces jointes',
    markAsUrgent: 'Marquer comme urgent',
    
    // Mentor
    mentor: 'Mentor',
    mentorPanel: 'Panneau de mentor',
    reviewAndManage: 'Examiner et gérer les soumissions',
    reviewQueue: 'File de révision',
    approvedProblems: 'Problèmes approuvés',
    approve: 'Approuver',
    reject: 'Rejeter',
    highlight: 'Mettre en évidence',
    assignToMe: 'M\'assigner',
    mentorAssigned: 'Mentor assigné',
    highlighted: 'Mis en évidence',
    topPicks: 'Meilleurs choix',
    all: 'Tous',
    pending: 'En attente',
    aiGenerator: 'Générateur IA',
    
    // Profile
    profile: 'Profil',
    editProfile: 'Modifier le profil',
    changePhoto: 'Changer la photo',
    statistics: 'Statistiques',
    submitted: 'Soumis',
    bookmarks: 'Favoris',
    settings: 'Paramètres',
    help: 'Aide et support',
    about: 'À propos',
    logout: 'Déconnexion',
    
    // Settings
    settingsTitle: '⚙️ Paramètres',
    notifications: '🔔 NOTIFICATIONS',
    enableNotifications: 'Activer les notifications',
    receiveAllNotifications: 'Recevoir toutes les notifications',
    emailNotifications: 'Notifications par e-mail',
    receiveByEmail: 'Recevoir des mises à jour par e-mail',
    pushNotifications: 'Notifications push',
    receivePush: 'Recevoir des notifications push',
    problemUpdates: 'Mises à jour des problèmes',
    notifyProblemChanges: 'Notifier les changements de problèmes',
    mentorFeedback: 'Retour du mentor',
    notifyMentorReviews: 'Notifier les révisions des mentors',
    general: '🛠️ GÉNÉRAL',
    autoSaveDrafts: 'Enregistrer automatiquement',
    autoSaveDraftsSub: 'Enregistrer automatiquement les brouillons',
    soundEffects: 'Effets sonores',
    soundEffectsSub: 'Jouer des sons pour les actions',
    language: 'Langue',
    privacySecurity: '🔒 CONFIDENTIALITÉ ET SÉCURITÉ',
    privacySettings: 'Paramètres de confidentialité',
    dataUsage: 'Utilisation des données',
    accountSecurity: 'Sécurité du compte',
    clearCache: 'Vider le cache',
    
    // Language Modal
    selectLanguage: '🌍 Sélectionner la langue',
    languageChanged: 'Langue changée',
    languageChangedMsg: 'La langue a été changée avec succès!',
    
    // Common
    save: 'Enregistrer',
    cancel: 'Annuler',
    delete: 'Supprimer',
    edit: 'Modifier',
    close: 'Fermer',
    ok: 'OK',
    yes: 'Oui',
    no: 'Non',
    loading: 'Chargement...',
    error: 'Erreur',
    success: 'Succès',
  },
  
  it: {
    // Dashboard
    dashboard: 'Cruscotto',
    home: 'Home',
    overview: '📊 Panoramica',
    totalProblems: 'Problemi totali',
    pendingReview: 'In attesa di revisione',
    approved: 'Approvato',
    urgent: 'Urgente',
    quickActions: '⚡ Azioni rapide',
    submitProblem: 'Invia problema',
    viewAllProblems: 'Visualizza tutti i problemi',
    browseProblems: 'Sfoglia problemi',
    generateAI: 'Genera con AI',
    myProfile: 'Il mio profilo',
    recentActivity: '📈 Attività recente',
    viewAll: 'Visualizza tutto',
    seeAll: 'Vedi tutto',
    
    // Problems
    problems: 'Problemi',
    problemStatements: 'Dichiarazioni dei problemi',
    browseAllProblems: 'Sfoglia tutti i problemi dell\'hackathon',
    allProblems: 'Tutti i problemi',
    mySubmissions: 'Le mie invii',
    bookmarked: 'Preferiti',
    searchProblems: 'Cerca problemi...',
    filters: 'Filtri',
    urgentOnly: 'Solo urgenti',
    clearAll: 'Cancella tutto',
    category: 'Categoria',
    difficulty: 'Difficoltà',
    problemsFound: 'problemi trovati',
    noProblemsFound: 'Nessun problema trovato',
    tryAdjustingFilters: 'Prova a regolare i filtri o invia un nuovo problema!',
    
    // Submit Problem
    submit: 'Invia',
    submitProblemStatement: 'Invia dichiarazione del problema',
    problemTitle: 'Titolo del problema',
    enterTitlePlaceholder: 'Inserisci un titolo chiaro e conciso',
    provideDetailedDescription: 'Fornisci una descrizione dettagliata del problema',
    constraints: 'Vincoli',
    addConstraintPlaceholder: 'Aggiungi un vincolo e premi +',
    requirements: 'Requisiti',
    addRequirementPlaceholder: 'Aggiungi un requisito e premi +',
    addTagsPlaceholder: 'Aggiungi tag per una migliore scoperta',
    attachmentsOptional: 'Allegati (opzionale)',
    uploadFilesOrImages: 'Carica file o immagini',
    problemSubmittedSuccess: 'Problema inviato con successo!',
    difficultyLevel: 'Livello di difficoltà',
    title: 'Titolo',
    description: 'Descrizione',
    tags: 'Tag',
    attachments: 'Allegati',
    markAsUrgent: 'Segna come urgente',
    
    // Mentor
    mentor: 'Mentore',
    mentorPanel: 'Pannello mentore',
    reviewAndManage: 'Rivedi e gestisci le invii',
    reviewQueue: 'Coda di revisione',
    approvedProblems: 'Problemi approvati',
    approve: 'Approva',
    reject: 'Rifiuta',
    highlight: 'Evidenzia',
    assignToMe: 'Assegna a me',
    mentorAssigned: 'Mentore assegnato',
    highlighted: 'Evidenziato',
    topPicks: 'Migliori scelte',
    all: 'Tutti',
    pending: 'In attesa',
    aiGenerator: 'Generatore IA',
    
    // Profile
    profile: 'Profilo',
    settings: 'Impostazioni',
    logout: 'Disconnetti',
    
    // Settings
    settingsTitle: '⚙️ Impostazioni',
    language: 'Lingua',
    selectLanguage: '🌍 Seleziona lingua',
    
    // Common
    save: 'Salva',
    cancel: 'Annulla',
    close: 'Chiudi',
    ok: 'OK',
  },
  
  hi: {
    // Dashboard
    dashboard: 'डैशबोर्ड',
    home: 'होम',
    overview: '📊 अवलोकन',
    totalProblems: 'कुल समस्याएं',
    pendingReview: 'समीक्षा लंबित',
    approved: 'स्वीकृत',
    urgent: 'जरूरी',
    quickActions: '⚡ त्वरित कार्य',
    submitProblem: 'समस्या जमा करें',
    viewAllProblems: 'सभी समस्याएं देखें',
    browseProblems: 'समस्याएं ब्राउज़ करें',
    generateAI: 'AI से जेनरेट करें',
    myProfile: 'मेरा प्रोफ़ाइल',
    recentActivity: '📈 हाल की गतिविधि',
    viewAll: 'सभी देखें',
    seeAll: 'सभी देखें',
    
    // Problems
    problems: 'समस्याएं',
    problemStatements: 'समस्या विवरण',
    browseAllProblems: 'सभी हैकथॉन समस्याएं ब्राउज़ करें',
    allProblems: 'सभी समस्याएं',
    mySubmissions: 'मेरे सबमिशन',
    bookmarked: 'बुकमार्क किए गए',
    searchProblems: 'समस्याएं खोजें...',
    filters: 'फ़िल्टर',
    urgentOnly: 'केवल जरूरी',
    clearAll: 'सभी साफ़ करें',
    category: 'श्रेणी',
    difficulty: 'कठिनाई',
    problemsFound: 'समस्याएं मिलीं',
    noProblemsFound: 'कोई समस्या नहीं मिली',
    tryAdjustingFilters: 'अपने फ़िल्टर समायोजित करें या नई समस्या जमा करें!',
    
    // Submit Problem
    submit: 'जमा करें',
    submitProblemStatement: 'समस्या विवरण जमा करें',
    problemTitle: 'समस्या का शीर्षक',
    enterTitlePlaceholder: 'एक स्पष्ट और संक्षिप्त शीर्षक दर्ज करें',
    provideDetailedDescription: 'समस्या का विस्तृत विवरण प्रदान करें',
    constraints: 'बाधाएं',
    addConstraintPlaceholder: 'एक बाधा जोड़ें और + दबाएं',
    requirements: 'आवश्यकताएं',
    addRequirementPlaceholder: 'एक आवश्यकता जोड़ें और + दबाएं',
    addTagsPlaceholder: 'बेहतर खोज के लिए टैग जोड़ें',
    attachmentsOptional: 'अटैचमेंट (वैकल्पिक)',
    uploadFilesOrImages: 'फ़ाइलें या छवियां अपलोड करें',
    problemSubmittedSuccess: 'समस्या सफलतापूर्वक जमा की गई!',
    difficultyLevel: 'कठिनाई स्तर',
    title: 'शीर्षक',
    description: 'विवरण',
    tags: 'टैग',
    attachments: 'अटैचमेंट',
    markAsUrgent: 'जरूरी के रूप में चिह्नित करें',
    
    // Mentor
    mentor: 'मेंटर',
    mentorPanel: 'मेंटर पैनल',
    reviewAndManage: 'सबमिशन की समीक्षा और प्रबंधन करें',
    reviewQueue: 'समीक्षा कतार',
    approvedProblems: 'स्वीकृत समस्याएं',
    approve: 'स्वीकृत करें',
    reject: 'अस्वीकार करें',
    highlight: 'हाइलाइट करें',
    assignToMe: 'मुझे सौंपें',
    mentorAssigned: 'मेंटर सौंपा गया',
    highlighted: 'हाइलाइट किया गया',
    topPicks: 'शीर्ष चयन',
    all: 'सभी',
    pending: 'लंबित',
    aiGenerator: 'AI जेनरेटर',
    
    // Profile
    profile: 'प्रोफ़ाइल',
    settings: 'सेटिंग्स',
    logout: 'लॉगआउट',
    
    // Settings
    settingsTitle: '⚙️ सेटिंग्स',
    language: 'भाषा',
    selectLanguage: '🌍 भाषा चुनें',
    
    // Common
    save: 'सहेजें',
    cancel: 'रद्द करें',
    close: 'बंद करें',
    ok: 'ठीक है',
  },
  
  es: {
    // Dashboard
    dashboard: 'Panel de control',
    home: 'Inicio',
    overview: '📊 Resumen',
    totalProblems: 'Problemas totales',
    pendingReview: 'Revisión pendiente',
    approved: 'Aprobado',
    urgent: 'Urgente',
    quickActions: '⚡ Acciones rápidas',
    submitProblem: 'Enviar problema',
    viewAllProblems: 'Ver todos los problemas',
    browseProblems: 'Explorar problemas',
    generateAI: 'Generar con IA',
    myProfile: 'Mi perfil',
    recentActivity: '📈 Actividad reciente',
    viewAll: 'Ver todo',
    seeAll: 'Ver todo',
    
    // Problems
    problems: 'Problemas',
    problemStatements: 'Enunciados de problemas',
    browseAllProblems: 'Explorar todos los problemas del hackathon',
    allProblems: 'Todos los problemas',
    mySubmissions: 'Mis envíos',
    bookmarked: 'Marcados',
    searchProblems: 'Buscar problemas...',
    filters: 'Filtros',
    urgentOnly: 'Solo urgentes',
    clearAll: 'Borrar todo',
    category: 'Categoría',
    difficulty: 'Dificultad',
    problemsFound: 'problemas encontrados',
    noProblemsFound: 'No se encontraron problemas',
    tryAdjustingFilters: '¡Intenta ajustar tus filtros o envía un nuevo problema!',
    
    // Submit Problem
    submit: 'Enviar',
    submitProblemStatement: 'Enviar enunciado de problema',
    problemTitle: 'Título del problema',
    enterTitlePlaceholder: 'Ingrese un título claro y conciso',
    provideDetailedDescription: 'Proporcione una descripción detallada del problema',
    constraints: 'Restricciones',
    addConstraintPlaceholder: 'Agregue una restricción y presione +',
    requirements: 'Requisitos',
    addRequirementPlaceholder: 'Agregue un requisito y presione +',
    addTagsPlaceholder: 'Agregue etiquetas para mejor descubrimiento',
    attachmentsOptional: 'Archivos adjuntos (opcional)',
    uploadFilesOrImages: 'Subir archivos o imágenes',
    problemSubmittedSuccess: '¡Problema enviado con éxito!',
    difficultyLevel: 'Nivel de dificultad',
    title: 'Título',
    description: 'Descripción',
    tags: 'Etiquetas',
    attachments: 'Archivos adjuntos',
    markAsUrgent: 'Marcar como urgente',
    
    // Mentor
    mentor: 'Mentor',
    mentorPanel: 'Panel de mentor',
    reviewAndManage: 'Revisar y gestionar envíos',
    reviewQueue: 'Cola de revisión',
    approvedProblems: 'Problemas aprobados',
    approve: 'Aprobar',
    reject: 'Rechazar',
    highlight: 'Destacar',
    assignToMe: 'Asignarme',
    mentorAssigned: 'Mentor asignado',
    highlighted: 'Destacado',
    topPicks: 'Mejores selecciones',
    all: 'Todos',
    pending: 'Pendiente',
    aiGenerator: 'Generador IA',
    
    // Profile
    profile: 'Perfil',
    settings: 'Configuración',
    logout: 'Cerrar sesión',
    
    // Settings
    settingsTitle: '⚙️ Configuración',
    language: 'Idioma',
    selectLanguage: '🌍 Seleccionar idioma',
    
    // Common
    save: 'Guardar',
    cancel: 'Cancelar',
    close: 'Cerrar',
    ok: 'OK',
  },
  
  de: {
    // Dashboard
    dashboard: 'Dashboard',
    home: 'Startseite',
    overview: '📊 Übersicht',
    totalProblems: 'Gesamte Probleme',
    pendingReview: 'Ausstehende Überprüfung',
    approved: 'Genehmigt',
    urgent: 'Dringend',
    quickActions: '⚡ Schnellaktionen',
    submitProblem: 'Problem einreichen',
    viewAllProblems: 'Alle Probleme anzeigen',
    browseProblems: 'Probleme durchsuchen',
    generateAI: 'Mit KI generieren',
    myProfile: 'Mein Profil',
    recentActivity: '📈 Letzte Aktivität',
    viewAll: 'Alles anzeigen',
    seeAll: 'Alles anzeigen',
    
    // Problems
    problems: 'Probleme',
    problemStatements: 'Problemstellungen',
    browseAllProblems: 'Alle Hackathon-Probleme durchsuchen',
    allProblems: 'Alle Probleme',
    mySubmissions: 'Meine Einreichungen',
    bookmarked: 'Lesezeichen',
    searchProblems: 'Probleme suchen...',
    filters: 'Filter',
    urgentOnly: 'Nur dringend',
    clearAll: 'Alles löschen',
    category: 'Kategorie',
    difficulty: 'Schwierigkeit',
    problemsFound: 'Probleme gefunden',
    noProblemsFound: 'Keine Probleme gefunden',
    tryAdjustingFilters: 'Versuchen Sie, Ihre Filter anzupassen oder ein neues Problem einzureichen!',
    
    // Submit Problem
    submit: 'Einreichen',
    submitProblemStatement: 'Problemstellung einreichen',
    problemTitle: 'Problemtitel',
    enterTitlePlaceholder: 'Geben Sie einen klaren und prägnanten Titel ein',
    provideDetailedDescription: 'Geben Sie eine detaillierte Beschreibung des Problems',
    constraints: 'Einschränkungen',
    addConstraintPlaceholder: 'Einschränkung hinzufügen und + drücken',
    requirements: 'Anforderungen',
    addRequirementPlaceholder: 'Anforderung hinzufügen und + drücken',
    addTagsPlaceholder: 'Tags für bessere Auffindbarkeit hinzufügen',
    attachmentsOptional: 'Anhänge (optional)',
    uploadFilesOrImages: 'Dateien oder Bilder hochladen',
    problemSubmittedSuccess: 'Problem erfolgreich eingereicht!',
    difficultyLevel: 'Schwierigkeitsgrad',
    title: 'Titel',
    description: 'Beschreibung',
    tags: 'Tags',
    attachments: 'Anhänge',
    markAsUrgent: 'Als dringend markieren',
    
    // Mentor
    mentor: 'Mentor',
    mentorPanel: 'Mentor-Panel',
    reviewAndManage: 'Einreichungen überprüfen und verwalten',
    reviewQueue: 'Überprüfungswarteschlange',
    approvedProblems: 'Genehmigte Probleme',
    approve: 'Genehmigen',
    reject: 'Ablehnen',
    highlight: 'Hervorheben',
    assignToMe: 'Mir zuweisen',
    mentorAssigned: 'Mentor zugewiesen',
    highlighted: 'Hervorgehoben',
    topPicks: 'Top-Auswahl',
    all: 'Alle',
    pending: 'Ausstehend',
    aiGenerator: 'KI-Generator',
    
    // Profile
    profile: 'Profil',
    settings: 'Einstellungen',
    logout: 'Abmelden',
    
    // Settings
    settingsTitle: '⚙️ Einstellungen',
    language: 'Sprache',
    selectLanguage: '🌍 Sprache auswählen',
    
    // Common
    save: 'Speichern',
    cancel: 'Abbrechen',
    close: 'Schließen',
    ok: 'OK',
  },
};

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState('en');

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
