import { ProblemStatement, User } from '../types';

export const mockUser: User = {
  id: '1',
  name: 'Alex Johnson',
  email: 'alex@hackintake.com',
  role: 'mentor',
};

export const sampleProblems: ProblemStatement[] = [
  {
    id: '1',
    title: 'Smart Campus Navigation System',
    category: 'Mobile Development',
    difficulty: 'Medium',
    description:
      'Design and develop a mobile app that helps students navigate large university campuses using AR technology. The app should provide real-time directions, show building information, and include accessibility features.',
    constraints: [
      'Must work offline with cached maps',
      'Battery usage should be optimized',
      'Support for iOS and Android',
    ],
    requirements: [
      'AR wayfinding feature',
      'Accessibility mode for disabled students',
      'Integration with campus events calendar',
      'Real-time crowding information',
    ],
    tags: ['AR', 'Navigation', 'Accessibility', 'Education'],
    urgent: false,
    status: 'approved',
    createdBy: '1',
    createdAt: new Date('2025-11-01'),
    updatedAt: new Date('2025-11-02'),
    aiScore: 85,
    bookmarkedBy: [],
  },
  {
    id: '2',
    title: 'Climate Action Tracker',
    category: 'Web Development',
    difficulty: 'Hard',
    description:
      'Build a comprehensive web platform that tracks personal carbon footprint and suggests actionable steps to reduce environmental impact. Include gamification elements to encourage sustainable habits.',
    constraints: [
      'Must calculate accurate carbon emissions',
      'Data privacy is critical',
      'Cross-browser compatibility required',
    ],
    requirements: [
      'Personal carbon calculator',
      'Achievement badges and leaderboard',
      'Integration with smart home devices',
      'Monthly sustainability reports',
    ],
    tags: ['Sustainability', 'Environment', 'Gamification', 'IoT'],
    urgent: true,
    status: 'highlighted',
    createdBy: '1',
    createdAt: new Date('2025-10-28'),
    updatedAt: new Date('2025-11-03'),
    aiScore: 92,
    bookmarkedBy: [],
  },
  {
    id: '3',
    title: 'AI-Powered Healthcare Chatbot',
    category: 'AI/ML',
    difficulty: 'Expert',
    description:
      'Develop an intelligent chatbot that can provide preliminary medical advice, schedule appointments, and answer health-related queries. Must comply with healthcare regulations and ensure patient data security.',
    constraints: [
      'HIPAA compliance mandatory',
      'Multi-language support',
      'Response time under 2 seconds',
    ],
    requirements: [
      'Natural language understanding',
      'Symptom checker functionality',
      'Integration with hospital management systems',
      'Emergency escalation protocol',
    ],
    tags: ['AI', 'Healthcare', 'NLP', 'Chatbot'],
    urgent: true,
    status: 'pending',
    createdBy: '1',
    createdAt: new Date('2025-11-04'),
    updatedAt: new Date('2025-11-04'),
    aiScore: 88,
    bookmarkedBy: [],
  },
  {
    id: '4',
    title: 'Blockchain-Based Supply Chain Tracker',
    category: 'Blockchain',
    difficulty: 'Hard',
    description:
      'Create a decentralized application for tracking products through the supply chain, ensuring transparency and preventing counterfeit goods. Use smart contracts for automated verification.',
    constraints: [
      'Must be scalable for enterprise use',
      'Low transaction fees',
      'Immutable record keeping',
    ],
    requirements: [
      'QR code scanning',
      'Real-time tracking dashboard',
      'Smart contract integration',
      'Manufacturer and consumer portals',
    ],
    tags: ['Blockchain', 'Supply Chain', 'Ethereum', 'DApp'],
    urgent: false,
    status: 'approved',
    createdBy: '1',
    createdAt: new Date('2025-10-30'),
    updatedAt: new Date('2025-11-01'),
    aiScore: 79,
    bookmarkedBy: [],
  },
  {
    id: '5',
    title: 'Mental Health Support Platform',
    category: 'Web Development',
    difficulty: 'Medium',
    description:
      'Build a safe, anonymous platform where students can access mental health resources, connect with counselors, and participate in support groups. Focus on creating a stigma-free environment.',
    constraints: [
      'Complete anonymity must be maintained',
      '24/7 availability',
      'Crisis intervention features',
    ],
    requirements: [
      'Anonymous chat with counselors',
      'Resource library with articles and videos',
      'Peer support groups',
      'Mood tracking and journaling',
    ],
    tags: ['Mental Health', 'Wellbeing', 'Community', 'Support'],
    urgent: false,
    status: 'approved',
    createdBy: '1',
    createdAt: new Date('2025-11-02'),
    updatedAt: new Date('2025-11-03'),
    aiScore: 91,
    bookmarkedBy: [],
  },
];
