import { ProblemStatement, User } from '../types';

export const mockUser: User = {
  id: '1',
  name: 'Alex Johnson',
  email: 'alex@hackintake.com',
  role: 'mentor',
};

export const sampleProblems: ProblemStatement[] = [
  {
    id: '1',
    title: 'Smart Campus Navigation System',
    category: 'Mobile Development',
    difficulty: 'Medium',
    description:
      'Design and develop a mobile app that helps students navigate large university campuses using AR technology. The app should provide real-time directions, show building information, and include accessibility features.',
    constraints: [
      'Must work offline with cached maps',
      'Battery usage should be optimized',
      'Support for iOS and Android',
    ],
    requirements: [
      'AR wayfinding feature',
      'Accessibility mode for disabled students',
      'Integration with campus events calendar',
      'Real-time crowding information',
    ],
    tags: ['AR', 'Navigation', 'Accessibility', 'Education'],
    urgent: false,
    status: 'approved',
    createdBy: '1',
    createdAt: new Date('2025-11-01'),
    updatedAt: new Date('2025-11-02'),
    aiScore: 85,
    bookmarkedBy: [],
  },
  {
    id: '2',
    title: 'Climate Action Tracker',
    category: 'Web Development',
    difficulty: 'Hard',
    description:
      'Build a comprehensive web platform that tracks personal carbon footprint and suggests actionable steps to reduce environmental impact. Include gamification elements to encourage sustainable habits.',
    constraints: [
      'Must calculate accurate carbon emissions',
      'Data privacy is critical',
      'Cross-browser compatibility required',
    ],
    requirements: [
      'Personal carbon calculator',
      'Achievement badges and leaderboard',
      'Integration with smart home devices',
      'Monthly sustainability reports',
    ],
    tags: ['Sustainability', 'Environment', 'Gamification', 'IoT'],
    urgent: true,
    status: 'highlighted',
    createdBy: '1',
    createdAt: new Date('2025-10-28'),
    updatedAt: new Date('2025-11-03'),
    aiScore: 92,
    bookmarkedBy: [],
  },
  {
    id: '3',
    title: 'AI-Powered Healthcare Chatbot',
    category: 'AI/ML',
    difficulty: 'Expert',
    description:
      'Develop an intelligent chatbot that can provide preliminary medical advice, schedule appointments, and answer health-related queries. Must comply with healthcare regulations and ensure patient data security.',
    constraints: [
      'HIPAA compliance mandatory',
      'Multi-language support',
      'Response time under 2 seconds',
    ],
    requirements: [
      'Natural language understanding',
      'Symptom checker functionality',
      'Integration with hospital management systems',
      'Emergency escalation protocol',
    ],
    tags: ['AI', 'Healthcare', 'NLP', 'Chatbot'],
    urgent: true,
    status: 'pending',
    createdBy: '1',
    createdAt: new Date('2025-11-04'),
    updatedAt: new Date('2025-11-04'),
    aiScore: 88,
    bookmarkedBy: [],
  },
  {
    id: '4',
    title: 'Blockchain-Based Supply Chain Tracker',
    category: 'Blockchain',
    difficulty: 'Hard',
    description:
      'Create a decentralized application for tracking products through the supply chain, ensuring transparency and preventing counterfeit goods. Use smart contracts for automated verification.',
    constraints: [
      'Must be scalable for enterprise use',
      'Low transaction fees',
      'Immutable record keeping',
    ],
    requirements: [
      'QR code scanning',
      'Real-time tracking dashboard',
      'Smart contract integration',
      'Manufacturer and consumer portals',
    ],
    tags: ['Blockchain', 'Supply Chain', 'Ethereum', 'DApp'],
    urgent: false,
    status: 'approved',
    createdBy: '1',
    createdAt: new Date('2025-10-30'),
    updatedAt: new Date('2025-11-01'),
    aiScore: 79,
    bookmarkedBy: [],
  },
  {
    id: '5',
    title: 'Mental Health Support Platform',
    category: 'Web Development',
    difficulty: 'Medium',
    description:
      'Build a safe, anonymous platform where students can access mental health resources, connect with counselors, and participate in support groups. Focus on creating a stigma-free environment.',
    constraints: [
      'Complete anonymity must be maintained',
      '24/7 availability',
      'Crisis intervention features',
    ],
    requirements: [
      'Anonymous chat with counselors',
      'Resource library with articles and videos',
      'Peer support groups',
      'Mood tracking and journaling',
    ],
    tags: ['Mental Health', 'Wellbeing', 'Community', 'Support'],
    urgent: false,
    status: 'approved',
    createdBy: '1',
    createdAt: new Date('2025-11-02'),
    updatedAt: new Date('2025-11-03'),
    aiScore: 91,
    bookmarkedBy: [],
  },
  {
    id: '6',
    title: 'Recipe Sharing Social Network',
    category: 'Web Development',
    difficulty: 'Easy',
    description:
      'Create a social platform where users can share recipes, rate dishes, and follow their favorite chefs. Include features for dietary restrictions, meal planning, and grocery list generation.',
    constraints: [
      'Mobile-responsive design required',
      'Fast image loading and optimization',
      'Must support multiple languages',
    ],
    requirements: [
      'User profiles and following system',
      'Recipe upload with photos and videos',
      'Rating and review system',
      'Search and filter by ingredients/dietary needs',
      'Grocery list generator from recipes',
    ],
    tags: ['Social Media', 'Food', 'Community', 'React'],
    urgent: false,
    status: 'approved',
    createdBy: '2',
    createdAt: new Date('2025-10-25'),
    updatedAt: new Date('2025-10-26'),
    aiScore: 76,
    bookmarkedBy: [],
  },
  {
    id: '7',
    title: 'Local Event Discovery App',
    category: 'Mobile Development',
    difficulty: 'Easy',
    description:
      'Build a mobile app that helps users discover local events, concerts, workshops, and meetups in their area. Include features for booking tickets, creating reminders, and sharing events with friends.',
    constraints: [
      'Must use GPS for location detection',
      'Offline mode for saved events',
      'Push notifications for event reminders',
    ],
    requirements: [
      'Map view with event pins',
      'Calendar integration',
      'Social sharing capabilities',
      'Event categories and filtering',
      'Ticket booking integration',
    ],
    tags: ['Mobile', 'Social', 'Events', 'Location'],
    urgent: false,
    status: 'approved',
    createdBy: '2',
    createdAt: new Date('2025-10-27'),
    updatedAt: new Date('2025-10-28'),
    aiScore: 72,
    bookmarkedBy: [],
  },
  {
    id: '8',
    title: 'Personal Finance Tracker',
    category: 'Web Development',
    difficulty: 'Medium',
    description:
      'Develop a web application that helps users track income, expenses, and savings goals. Include budgeting tools, expense categorization, and financial insights with interactive charts.',
    constraints: [
      'Bank-level security required',
      'Data encryption for sensitive information',
      'Must work across all devices',
    ],
    requirements: [
      'Income and expense tracking',
      'Budget creation and monitoring',
      'Visual reports and charts',
      'Receipt scanning and storage',
      'Bill payment reminders',
    ],
    tags: ['Finance', 'Budgeting', 'Analytics', 'Security'],
    urgent: false,
    status: 'approved',
    createdBy: '3',
    createdAt: new Date('2025-10-29'),
    updatedAt: new Date('2025-10-30'),
    aiScore: 83,
    bookmarkedBy: [],
  },
  {
    id: '9',
    title: 'Virtual Study Room Platform',
    category: 'Web Development',
    difficulty: 'Medium',
    description:
      'Create a virtual study space where students can join video study sessions, share screens, collaborate on documents, and use the Pomodoro technique together. Gamify study time with rewards.',
    constraints: [
      'Stable video conferencing for up to 50 users',
      'Low latency for real-time collaboration',
      'Screen sharing without quality loss',
    ],
    requirements: [
      'Video chat rooms',
      'Shared whiteboard',
      'Document collaboration',
      'Pomodoro timer with breaks',
      'Study streak tracking and badges',
    ],
    tags: ['Education', 'Collaboration', 'Video', 'Productivity'],
    urgent: false,
    status: 'pending',
    createdBy: '3',
    createdAt: new Date('2025-11-05'),
    updatedAt: new Date('2025-11-05'),
    aiScore: 87,
    bookmarkedBy: [],
  },
  {
    id: '10',
    title: 'Smart Waste Management System',
    category: 'IoT',
    difficulty: 'Hard',
    description:
      'Design an IoT-based waste management system that uses sensors to monitor bin fill levels, optimize collection routes, and encourage recycling through a mobile app with rewards.',
    constraints: [
      'Sensors must be weatherproof',
      'Battery life of at least 6 months',
      'Real-time data synchronization',
    ],
    requirements: [
      'Smart bin sensors for fill level detection',
      'Route optimization algorithm for collectors',
      'Mobile app for citizens to report issues',
      'Recycling rewards and gamification',
      'Analytics dashboard for city officials',
    ],
    tags: ['IoT', 'Sustainability', 'Smart City', 'Hardware'],
    urgent: true,
    status: 'highlighted',
    createdBy: '4',
    createdAt: new Date('2025-11-03'),
    updatedAt: new Date('2025-11-04'),
    aiScore: 89,
    bookmarkedBy: [],
  },
  {
    id: '11',
    title: 'Language Learning Gamification App',
    category: 'Mobile Development',
    difficulty: 'Easy',
    description:
      'Build a fun, game-based language learning app that teaches vocabulary and grammar through interactive challenges, daily quests, and multiplayer competitions. Support at least 5 languages.',
    constraints: [
      'Must work offline for lessons',
      'Engaging UI/UX for all age groups',
      'Audio pronunciation quality must be clear',
    ],
    requirements: [
      'Daily challenges and streaks',
      'Multiplayer quiz battles',
      'Progress tracking with levels',
      'Native speaker audio clips',
      'Spaced repetition algorithm',
    ],
    tags: ['Education', 'Gamification', 'Mobile', 'Languages'],
    urgent: false,
    status: 'approved',
    createdBy: '4',
    createdAt: new Date('2025-10-26'),
    updatedAt: new Date('2025-10-27'),
    aiScore: 78,
    bookmarkedBy: [],
  },
  {
    id: '12',
    title: 'Freelancer Time Tracking Tool',
    category: 'Web Development',
    difficulty: 'Easy',
    description:
      'Create a simple time tracking application for freelancers to log hours, manage multiple projects, generate invoices, and analyze productivity patterns. Include client management features.',
    constraints: [
      'Must be intuitive and fast to use',
      'Data export in multiple formats',
      'Secure client information storage',
    ],
    requirements: [
      'Project and task time tracking',
      'Automatic invoice generation',
      'Client management portal',
      'Productivity analytics and reports',
      'Browser extension for quick time logging',
    ],
    tags: ['Productivity', 'Time Tracking', 'Freelance', 'SaaS'],
    urgent: false,
    status: 'approved',
    createdBy: '5',
    createdAt: new Date('2025-10-24'),
    updatedAt: new Date('2025-10-25'),
    aiScore: 74,
    bookmarkedBy: [],
  },
  {
    id: '13',
    title: 'Fitness Challenge Social App',
    category: 'Mobile Development',
    difficulty: 'Medium',
    description:
      'Develop a fitness app where users can create workout challenges, compete with friends, track progress, and share achievements. Include integration with fitness trackers and smartwatches.',
    constraints: [
      'Real-time synchronization across devices',
      'Support for popular fitness tracker APIs',
      'Privacy controls for health data',
    ],
    requirements: [
      'Challenge creation and participation',
      'Leaderboards and rankings',
      'Workout tracking and history',
      'Integration with Apple Health and Google Fit',
      'Social feed for sharing achievements',
    ],
    tags: ['Fitness', 'Health', 'Social', 'Wearables'],
    urgent: false,
    status: 'pending',
    createdBy: '5',
    createdAt: new Date('2025-11-06'),
    updatedAt: new Date('2025-11-06'),
    aiScore: 81,
    bookmarkedBy: [],
  },
  {
    id: '14',
    title: 'Neighborhood Safety Network',
    category: 'Mobile Development',
    difficulty: 'Medium',
    description:
      'Build a community-driven safety app where residents can report incidents, share alerts, connect with local authorities, and organize neighborhood watch programs. Include emergency SOS features.',
    constraints: [
      'Location privacy is critical',
      'Fast emergency alert delivery',
      'Moderation system to prevent spam',
    ],
    requirements: [
      'Incident reporting with photos',
      'Real-time safety alerts',
      'Direct communication with police',
      'SOS button with location sharing',
      'Community forums and meetups',
    ],
    tags: ['Safety', 'Community', 'Emergency', 'Location'],
    urgent: true,
    status: 'pending',
    createdBy: '6',
    createdAt: new Date('2025-11-07'),
    updatedAt: new Date('2025-11-07'),
    aiScore: 86,
    bookmarkedBy: [],
  },
  {
    id: '15',
    title: 'Digital Library Management System',
    category: 'Web Development',
    difficulty: 'Easy',
    description:
      'Create a web-based library system for schools and colleges to manage book inventory, track borrowing, send due date reminders, and allow students to search and reserve books online.',
    constraints: [
      'Must handle thousands of books',
      'Barcode scanning support',
      'Email and SMS notification system',
    ],
    requirements: [
      'Book catalog with search and filters',
      'Borrowing and return management',
      'Automated overdue notifications',
      'Student accounts and history',
      'Admin dashboard for librarians',
    ],
    tags: ['Education', 'Management', 'Database', 'Backend'],
    urgent: false,
    status: 'approved',
    createdBy: '6',
    createdAt: new Date('2025-10-23'),
    updatedAt: new Date('2025-10-24'),
    aiScore: 71,
    bookmarkedBy: [],
  },
];
